### ISSUE TITLE
FreeBSD compatibility

### ISSUE THREAD

**Issue by probonopd** [Phantop/appdwarf#2]
Interesting!

Would you think this is something a future version of the AppImage file format should consider to take advantage of?

It would be nice if the bash script would be replaced by a ELF executable binary in order to remove the dependencies on tools that may not be there, e.g., on FreeBSD (admittedly an edge case but hey, AppImages can run there thanks to the Linuxulator in FreeBSD).

```
FreeBSD% chmod +x /tmp/java
FreeBSD% file /tmp/java 
/tmp/java: POSIX shell script executable (binary data)
FreeBSD% /tmp/java 
/tmp/java: md5sum: not found
/tmp/java: [[: not found
/tmp/java: /tmp/dwarf_java/AppRun: not found
/tmp/java: fusermount: not found
```

**Comment by Drsheppard01** [comment]
@probonopd also worth a look at https://github.com/Kron4ek/Conty

**Comment by Phantop** [comment]
Oh hey, I really did not notice that there were issues open on this repo... GitHub just never emailed me, strangely.

I did in fact have that in mind, considering that is what AppImages do. I might do it someday, but the whole reason this is a shell script to begin with is that I frankly don't really have the time/skills to make a proper executable version of this as of now.

However, I am open to trying to minimize non-portable (barring dwarfs itself) tools being used! I'll give it a look over in a bit.

**Comment by Phantop** [comment]
I will quickly say to just outright ignore versioned releases and use the latest commit instead (should probably put a note of that in the README). I basically gave up on numbering them because I fiddle around with this script so much.

As for the actual things you noted:
- The script is compatible with POSIX sh and`[[` isn't used in the code anymore. You noting it is why I assume you used the versioned release
- I have pushed an updated commit that removes the `md5sum` invocation and instead just uses `mktemp`. I was using `md5sum` because I wanted to share mountpoints for multiple invocations of the same appdwarf, but honestly it didn't pan out and was too buggy to be worth keeping
- For `fusermount`, a quick search seems to indicate that FreeBSD doesn't have it. I'm a little unsure how users can unmount filesystems in FreeBSD without needing elevated privileges. It seems like users can just run unmount? But I'm a tad reluctant to add that unless I'm sure.

**Comment by Phantop** [comment]
Seeing as this issue hasn't changed in any way in over a year, and I have no intention of installing FreeBSD just to figure out compatibility, I'll be closing this issue.
