### ISSUE TITLE
Feature request: include the needed dwarfs executables in the generated file

### ISSUE THREAD

**Issue by M-Gonzalo** [Phantop/appdwarf#3]
So, even though dwarfs is arguably the very best at what it does, it's not really known or popular. Meaning, an AppImage using it can't really be published as is because most people won't be able to use it.
Now, what about a minimal squashfs image containing a portable version of a barebones dwarfs install, appended to the actual image of the program contents? That just might do.
The idea is to first execute dwarfs like a normal AppImage and use it to mount and execute the program transparently to the user.
Thoughts?

**Comment by Phantop** [comment]
So I have definitely given this some consideration in the past and am honestly somewhat unsure why I didn't just add it as an option before. Biggest issues to me are working out a way of getting the offset for the `dwarfs` executable I'm sufficiently happy with (which I could probably do by either searching for a squashfs header or the expected end of the header script) and that it means adding an alternative header script... though I suppose anything different *could* just be prepended to the existing header.

I *do* wonder whether expecting squashfs to be available is the ideal call, however. If I recall correctly, using it makes the end offset of it a non-issue, but I'm unsure how reliably we can expect its availability even when we can assume FUSE.

Regardless, I'll try some things later today.

**Comment by Phantop** [comment]
On the note of squashfs availability, now that I think about it I also believe that `squashfuse` needs to be installed to allow mounting squashfs images on an offset. I'm a little unsure on how commonly it's installed on typical distributions, so that needs to be looked into as well.

There is an alternate option of just compressing the `dwarfs` binary with `zstd` and storing the start and end offsets, at least. But of course that means any system *must* have a `zstd` binary. `gzip` could be used, but it's generally not as good so :woman_shrugging:. Maybe I'll just throw the binary in directly and leave it to the image creator to use `upx` or even `zzexe` on the binary.

**Comment by Phantop** [comment]
Added this in the latest commit. You can use the `--bundle /path/to/dwarfs` option to do this now. It requires `zstd` but should work as expected.

Stuff like this is making me increasingly think of redoing the header system to just store their offsets at some point. So many weird string ways of doing it that are starting to get kinda gross and cumbersome. Still, I personally don't use `zzexe` much and don't intend to make use of this bundling behavior myself, so we'll see how this goes.

**Comment by M-Gonzalo** [comment]
Thanks! Although I'n not sure you understood what I mean.
In my mind, an appdwarf is always just a normal AppImage. With a second appdwarf appended to it (the one we create). Just like an SFX stub and its payload, only instead of decompressing the payload, we execute it.
So there's no need to create a bundle every time.
You just need to make a normal AppImage of a working dwarfs, and ship it with AppDwarf as a required file. That would be your "SFX header". Always the same little file, independently of the contents of what some user might want to package.
As a "payload", there's a second AppImage, the actual one, that now can be loaded everywhere because dwarfs is available and ready to use.
The price is a slightly larger file (I believe just a few kb)
And the offset is always the size of the first AppImage, which is the same for each architecture, and is actually already present in the working dir of appdwarf.

**Comment by Phantop** [comment]
If I'm understanding you correctly, I don't think what you're suggesting is something particularly worth doing. It would create a dependency on AppImage for this behavior and somewhat complicate the mounting process to accomplish effectively the same thing. The AppImage runtime officially only supports DEFLATE compression and glibc, which is why I generally don't like AppImages in comparison to appdwarf, and is definitely larger than just a few kilobytes and cannot be compressed.

I'm a little unsure what is the issue with the current implementation? It allows you to easily supply any `dwarfs` binary and compresses it, only requiring `zstd` (which I imagine is likely going to be on most Linux systems at this point, especially if DwarFS is expected to be used. The actual header will be the same if you're supplying the same `dwarfs` binary to bundle. Hell, you could probably use `dwarfsck` to extract that header and reuse it yourself if you'd want to.

**Comment by M-Gonzalo** [comment]
Nothing wrong with current implementation. It's probably even better than what I suggested, given that you know more about these things than me. I was just making myself more clear.
Thanks again for your work. I'll take a look at it later.
